# Generated by Django 4.2.23 on 2025-09-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_contact_created_at_contact_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_deals', to='deals.company'),
        ),
        migrations.AlterField(
            model_name='dealcompany',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('partner', 'Партнёр'), ('supplier', 'Поставщик'), ('investor', 'Инвестор')], default='customer', max_length=20, verbose_name='Роль компании в сделке'),
        ),
        migrations.CreateModel(
            name='DealContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_deals', to='deals.contact')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_contacts', to='deals.deal')),
            ],
        ),
    ]
