# Generated by Django 4.2.24 on 2025-09-19 23:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_company_address_company_email_company_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Начало",
                    ),
                ),
                (
                    "remind_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Напомнить"
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "Нет"),
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                            ("yearly", "Ежегодно"),
                            ("custom", "Пользовательский интервал"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "custom_interval_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Используется только для пользовательской периодичности.",
                        null=True,
                        verbose_name="Интервал (дни)",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие",
                "verbose_name_plural": "Действия",
                "ordering": ["starts_at"],
            },
        ),
    ]
