# Generated by Django 4.2.23 on 2025-09-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_dealaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость сделки'),
        ),
    ]
