# Generated by Django 4.2.23 on 2025-09-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_deal_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
    ]
