# Generated by Django 4.2.23 on 2025-10-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_company_inn_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealaction',
            name='notify_before_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='За сколько минут до начала отправить напоминание.', null=True, verbose_name='Оповестить за (минут)'),
        ),
        migrations.AddField(
            model_name='dealaction',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Выполнено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
    ]
