# Generated by Django 4.2.23 on 2025-10-05 10:34

from django.db import migrations, models


def copy_minutes_to_value(apps, schema_editor):
    DealAction = apps.get_model('deals', 'DealAction')
    for action in DealAction.objects.all():
        minutes = getattr(action, 'notify_before_minutes', None)
        if minutes is not None:
            action.notify_before_value = minutes
            action.notify_before_unit = 'minutes'
            action.save(update_fields=['notify_before_value', 'notify_before_unit'])


def copy_value_to_minutes(apps, schema_editor):
    DealAction = apps.get_model('deals', 'DealAction')
    for action in DealAction.objects.all():
        value = getattr(action, 'notify_before_value', None)
        if value is not None:
            action.notify_before_minutes = value
            action.save(update_fields=['notify_before_minutes'])


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_dealaction_notify_before_minutes_dealaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealaction',
            name='notify_before_unit',
            field=models.CharField(blank=True, choices=[('minutes', 'минут'), ('hours', 'часов'), ('days', 'дней')], default='minutes', max_length=16, verbose_name='Единица оповещения'),
        ),
        migrations.AddField(
            model_name='dealaction',
            name='notify_before_value',
            field=models.PositiveIntegerField(blank=True, help_text='Число единиц времени до начала действия.', null=True, verbose_name='Оповестить за'),
        ),
        migrations.RunPython(copy_minutes_to_value, copy_value_to_minutes),
        migrations.RemoveField(
            model_name='dealaction',
            name='notify_before_minutes',
        ),
    ]
