# Generated by Django 4.2.23 on 2025-10-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_remove_dealaction_notify_before_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание сделки'),
        ),
        migrations.AlterField(
            model_name='dealaction',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'В процессе выполнения'), ('completed', 'Выполнено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
    ]
