# Generated by Django 4.2.23 on 2025-10-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_remove_dealaction_notify_before_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание сделки'),
        ),
        migrations.AlterField(
            model_name='dealaction',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'В процессе выполнения'), ('completed', 'Выполнено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ContactCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='deals.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='deals.contact')),
            ],
            options={
                'unique_together': {('contact', 'company')},
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='contacts', through='deals.ContactCompany', to='deals.company'),
        ),
    ]
